# Generated by Django 6.0.1 on 2026-01-25 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_display_levels'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessionitem',
            name='kind',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
