# Generated by Django 6.0.1 on 2026-01-31 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_add_project_name_and_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(blank=True, max_length=25, null=True, unique=True),
        ),
    ]
