# Generated by Django 6.0.1 on 2026-02-05 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_rename_archived_to_stale'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='archived',
            field=models.BooleanField(default=False),
        ),
    ]
