# Generated by Django 6.0.2 on 2026-03-14 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0055_session_search_version'),
    ]

    operations = [
        migrations.AddField(
            model_name='toolresultlink',
            name='extra',
            field=models.TextField(blank=True, null=True),
        ),
    ]
