# Generated by Django 6.0.2 on 2026-03-15 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0056_toolresultlink_extra'),
    ]

    operations = [
        migrations.AddField(
            model_name='toolresultlink',
            name='is_error',
            field=models.BooleanField(default=False),
        ),
    ]
