# Generated by Django 6.0.2 on 2026-03-19 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0060_sessioncron_and_processrun'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='slug',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
