# Generated by Django 6.0.2 on 2026-03-26 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0061_session_slug'),
        ('core', '0062_processrun_and_sessioncron'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='last_new_content_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='session',
            name='last_viewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
