# Generated by Django 6.0.4 on 2026-09-01 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0136_session_mute_on_user_turn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='peermessage',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('delivered', 'Delivered'), ('done', 'Done'), ('refused', 'Refused'), ('failed', 'Failed')], max_length=12),
        ),
    ]
