# Generated by Django 6.0.4 on 2026-09-04 10:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0137_peermessage_done_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='peermessage',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='peer_messages', to='core.project'),
        ),
    ]
