# Generated by Django 6.0.4 on 2026-09-04 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0138_peermessage_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='unavailable_reason',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
