# Generated by Django 6.0.4 on 2026-09-05 16:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0139_session_unavailable_reason'),
    ]

    operations = [
        migrations.CreateModel(
            name='McpOAuthClient',
            fields=[
                ('id', models.CharField(max_length=2048, primary_key=True, serialize=False)),
                ('metadata', models.JSONField(default=dict)),
                ('secret_hash', models.CharField(blank=True, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='McpConnection',
            fields=[
                ('id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=80)),
                ('resource', models.URLField(max_length=2048)),
                ('established_at', models.DateTimeField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_used_at', models.DateTimeField(null=True)),
                ('revoked_at', models.DateTimeField(null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.mcpoauthclient')),
            ],
        ),
        migrations.CreateModel(
            name='McpOAuthCredential',
            fields=[
                ('digest', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('kind', models.CharField(max_length=16)),
                ('params', models.JSONField(default=dict)),
                ('consumed', models.BooleanField(default=False)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('connection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.mcpconnection')),
            ],
        ),
        migrations.CreateModel(
            name='McpOAuthRequest',
            fields=[
                ('id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('params', models.JSONField(default=dict)),
                ('continuation_hash', models.CharField(max_length=64)),
                ('verification_hash', models.CharField(max_length=64)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('state', models.CharField(default='pending', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.mcpoauthclient')),
                ('connection', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.mcpconnection')),
            ],
        ),
        migrations.CreateModel(
            name='McpOperation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=80)),
                ('tool', models.CharField(max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('targets', models.JSONField(default=dict)),
                ('connection', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.mcpconnection')),
            ],
        ),
    ]
