# Generated by Django 6.0.4 on 2026-09-07 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0142_flatten_codex_subagent_parents'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mcpoperation',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
    ]
