# Generated by Django 6.0.4 on 2026-09-25 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0144_delete_modelbenchmark'),
    ]

    operations = [
        migrations.AddField(
            model_name='processrun',
            name='background_work_in_progress',
            field=models.JSONField(blank=True, default=None, null=True),
        ),
    ]
