# Generated by Django 6.0.4 on 2026-09-27 05:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0145_processrun_background_work_in_progress'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentInteraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tool_use_line_num', models.PositiveIntegerField()),
                ('event_line_num', models.PositiveIntegerField()),
                ('tool_use_id', models.CharField(max_length=255)),
                ('agent_id', models.CharField(max_length=255)),
                ('kind', models.CharField(choices=[('message', 'Message'), ('resume', 'Resume'), ('stop', 'Stop'), ('output', 'Output')], max_length=20)),
                ('opens_run', models.BooleanField(default=False)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='AgentRunEnd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_num', models.PositiveIntegerField(blank=True, null=True)),
                ('source', models.CharField(choices=[('transcript', 'Transcript'), ('ui', 'Ui')], default='transcript', max_length=20)),
                ('agent_id', models.CharField(max_length=255)),
                ('tool_use_id', models.CharField(default='', max_length=255)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(blank=True, max_length=32, null=True)),
            ],
        ),
        migrations.AddIndex(
            model_name='agentlink',
            index=models.Index(fields=['agent_id'], name='idx_agent_link_agent'),
        ),
        migrations.AddIndex(
            model_name='toolresultlink',
            index=models.Index(fields=['session', 'tool_use_id'], name='idx_tool_result_link_by_tool'),
        ),
        migrations.AddField(
            model_name='agentinteraction',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_interactions', to='core.session'),
        ),
        migrations.AddField(
            model_name='agentrunend',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_run_ends', to='core.session'),
        ),
        migrations.AddIndex(
            model_name='agentinteraction',
            index=models.Index(fields=['agent_id'], name='idx_agent_interaction_agent'),
        ),
        migrations.AddConstraint(
            model_name='agentinteraction',
            constraint=models.UniqueConstraint(fields=('session', 'tool_use_id'), name='uniq_agent_interaction_call'),
        ),
        migrations.AddIndex(
            model_name='agentrunend',
            index=models.Index(fields=['agent_id', 'tool_use_id'], name='idx_agent_run_end_agent_tool'),
        ),
        migrations.AddConstraint(
            model_name='agentrunend',
            constraint=models.UniqueConstraint(condition=models.Q(('source', 'transcript')), fields=('session', 'line_num', 'tool_use_id'), name='uniq_agent_run_end_transcript'),
        ),
    ]
