# Generated by Django 6.0.4 on 2026-09-29 08:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0146_agent_runs'),
    ]

    operations = [
        migrations.CreateModel(
            name='SessionHistoryFact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_num', models.PositiveIntegerField()),
                ('kind', models.CharField(choices=[('tool_call', 'Tool call'), ('process_start', 'Process start'), ('code_cell', 'Code cell'), ('agent_spawn', 'Agent spawn'), ('turn_start', 'Turn start'), ('code_exec_target', 'Code exec target'), ('turn_context', 'Turn context'), ('plan_marker', 'Plan marker'), ('goal_context', 'Goal context'), ('goal_update', 'Goal update'), ('token_usage', 'Token usage')], max_length=32)),
                ('key', models.TextField()),
                ('data', models.JSONField()),
                ('session', models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.CASCADE, related_name='history_facts', to='core.session')),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('line_num__gte', 1)), name='history_fact_positive_line'), models.UniqueConstraint(fields=('session', 'kind', 'key', 'line_num'), name='uniq_history_fact_source')],
            },
        ),
    ]
