# Generated by Django 6.0.4 on 2026-09-29 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0147_session_history_fact'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='session',
            index=models.Index(condition=models.Q(('self_cost__isnull', False)), fields=['parent_session'], name='idx_session_parent_cost'),
        ),
        migrations.AddIndex(
            model_name='sessionitem',
            index=models.Index(fields=['session', 'message_id', 'line_num'], name='idx_item_message_line'),
        ),
    ]
