# Generated by Django 6.0.4 on 2026-09-30 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('core', '0148_live_contribution_indexes'), ('core', '0149_remove_redundant_message_index')]

    dependencies = [
        ('core', '0147_session_history_fact'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='session',
            index=models.Index(condition=models.Q(('self_cost__isnull', False)), fields=['parent_session'], name='idx_session_parent_cost'),
        ),
    ]
