# Generated by Django 6.0.4 on 2026-10-05 10:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0150_session_automatic_titles"),
    ]

    operations = [
        migrations.CreateModel(
            name="AsyncQuestionState",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("state", models.JSONField(default=dict)),
                (
                    "session",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="async_question_state",
                        to="core.session",
                    ),
                ),
            ],
        ),
    ]
