# Generated by Django 6.0.4 on 2026-10-04 07:28

import django.db.models.deletion
import twicc.core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0150_session_automatic_titles'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='history_epoch',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='McpEventSubscription',
            fields=[
                ('id', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64)),
                ('arguments', models.JSONField()),
                ('session_id', models.CharField(db_index=True, max_length=255)),
                ('callback_url', models.URLField(max_length=2048)),
                ('secret', models.CharField(max_length=128)),
                ('previous_secret', models.CharField(blank=True, max_length=128)),
                ('previous_secret_until', models.DateTimeField(null=True)),
                ('cursor_line', models.PositiveIntegerField()),
                ('cursor_at', models.FloatField()),
                ('initial_last_line', models.PositiveIntegerField()),
                ('turn_open', models.BooleanField()),
                ('turn_started_at', models.FloatField(null=True)),
                ('turn_opened_by', models.CharField(blank=True, max_length=16)),
                ('turn_start_line', models.PositiveIntegerField()),
                ('numbering', models.PositiveIntegerField(null=True)),
                ('data_dir', models.CharField(default=twicc.core.models.mcp_event_data_dir, max_length=4096)),
                ('refresh_before', models.DateTimeField(db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('connection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.mcpconnection')),
            ],
        ),
    ]
