# Generated by Django 6.0.4 on 2026-10-08 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0153_peer_message_attachments'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='inline_artifacts',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='share',
            name='inline_artifact_exports',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
